/**
 * Image manifest types for ModernSaaS landing page
 * Auto-generated by scripts/fetch-images.ts
 */

export type ImageCategory = 'tech' | 'abstract' | 'team' | 'office' | 'devices';

export interface ImageManifest {
  filename: string;
  category: ImageCategory;
  attribution: string;
  dimensions: {
    width: number;
    height: number;
  };
}

export interface ImageManifestFile {
  generated: string;
  totalImages: number;
  categories: Record<ImageCategory, number>;
  images: ImageManifest[];
}

export const IMAGE_CATEGORIES: ImageCategory[] = ['tech', 'abstract', 'team', 'office', 'devices'];

export function getImagesByCategory(
  manifest: ImageManifestFile,
  category: ImageCategory,
): ImageManifest[] {
  return manifest.images.filter((img) => img.category === category);
}
