name: Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    env:
      CI: true
      NODE_ENV: test

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18.x, 20.x, 22.x]
      fail-fast: false

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install dependencies (fallback)
        if: failure()
        run: npm install

      - name: Run tests
        run: npm test
        continue-on-error: false

      - name: Build production website
        run: npm run build
        continue-on-error: false

      - name: Upload build artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.os }}-${{ matrix.node }}
          path: |
            npm-debug.log*
            yarn-error.log*
            .npm/_logs/
